-- MySQL Script generated by MySQL Workbench
-- Fri Jul 12 21:56:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_codigo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_codigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_codigo` DEFAULT CHARACTER SET utf8 ;
USE `db_codigo` ;

-- -----------------------------------------------------
-- Table `db_codigo`.`tbl_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`tbl_alumno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`tbl_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`tbl_grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `bootcamp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`tbl_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`tbl_modulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`tbl_matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`tbl_matricula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alumno_id` INT NOT NULL,
  `grupo_id` INT NOT NULL,
  `modulo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_matricula_tbl_alumno_idx` (`alumno_id` ASC) VISIBLE,
  INDEX `fk_tbl_matricula_tbl_grupo1_idx` (`grupo_id` ASC) VISIBLE,
  INDEX `fk_tbl_matricula_tbl_modulo1_idx` (`modulo_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_matricula_tbl_alumno`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db_codigo`.`tbl_alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_tbl_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `db_codigo`.`tbl_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_tbl_modulo1`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `db_codigo`.`tbl_modulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
